/*
USE [ORACLE_SIM]
GO
DELETE FROM [dbo].[UPS100F]
GO
*/
/*
SELECT MSN FROM [ORACLE_SIM].[dbo].[UPS100F]

SELECT SHIPDATE FROM [ORACLE_SIM].[dbo].[UPS100F] WHERE SHIPDATE >= '03-16-2015';
*/
/*
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F] WHERE LEN(CAST(SHIPPER_REFERENCE AS VARCHAR)) > 0
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F_Archived] WHERE LEN(CAST(SHIPPER_REFERENCE AS VARCHAR)) > 0
*/
/*
SELECT convert(date, GETDATE() - 1)
INSERT INTO [ORACLE_SIM].[dbo].[UPS100F_Archived]
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F] WHERE SHIPDATE < convert(date, GETDATE() - (365 * 2));
DELETE FROM [ORACLE_SIM].[dbo].[UPS100F] WHERE SHIPDATE >= '03/16/2015';
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F_Archived];

INSERT INTO [ORACLE_SIM].[dbo].[UPS100F]
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F_Archived];
DELETE FROM [ORACLE_SIM].[dbo].[UPS100F_Archived];
SELECT * FROM [ORACLE_SIM].[dbo].[UPS100F];
*/
/*
INSERT into ORACLE_SIM.dbo.UPS100F (CS_Workstation, SHIPPER_REFERENCE, CONSIGNEE_REFERENCE, REF_1, REF_2, REF_3, SHIPDATE, DIMENSION, TOTAL, WEIGHT, TTL_FREIGHT, TTL_WEIGHT, DESCRIPTION, CURRENT_PACKAGE, TOTAL_PACKAGES, MSN, SERVICE, PACKAGING, COMPANY, CONTACT, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATEPROVINCE, POSTALCODE, COUNTRYSYMBOL, TRACKING_NUMBER, TERMS, SHIPPER, ARRIVE_DATE, COD_AMOUNT, CODE, UPINVOICE, COMMODITY_CLASS, BASE_CHARGE, RESIDENTIAL_CHARGE, FUEL_SURCHARGE, ACCESSORIAL_CHARGE, UPZONE )
values ('KEVIN', 'SHIPPER_REFERENCE', 'CONSIGNEE_REFERENCE', '12364567', '01', 'REF3', '03-16-2017', '0x0x0', '12.89', '14.5', '10.05', '10.05', 'TESTdescript', '1', '1', '123456', 'UPS_Ground' , 'packaging', 'PBD Worldwide', 'TestContact' , '1650 Bluegrass Lakes Pkwy', '', '', 'Alpharetta', 'GA', '30004', 'UNITED_STATES', '123456987ZXC' , 'DDU', 'ALPHA', '03/16/2017', '12.55', '123BAR456CODE' , 'reference18', 'CommClass', '12.55', '3.50', '0.00', '1.00', '6');
*/
/*
RAISERROR('Please enter a CustomerID',16,2)
*/